### ISSUE TITLE
not compatible with this engine

### ISSUE THREAD

**Issue by nengqi** [zurawiki/gptcommit#46] opened 2023-02-06 06:15 UTC
gc
🤖 Asking GPT-3 to summarize diffs...
Error: Unexpected JSON response:
{"error":{"code":null,"message":"You requested a model that is not compatible with this engine. Please contact us through our help center at help.openai.com for further questions.","param":"model","type":"invalid_request_error"}}

**Comment by zurawiki** [comment] 2023-02-06 15:23
It seems that the model you are using has some issues. Does the problem persist with a different model?

**Comment by nengqi** [comment] 2023-02-07 06:08
<img width="488" alt="image" src="https://user-images.githubusercontent.com/32950454/217162470-4999eefd-512e-41d5-b0ff-e62a7639f84b.png">


> It seems that the model you are using has some issues. Does the problem persist with a different model?

**Comment by zurawiki** [comment] 2023-02-07 13:59
Got it. Looks like the default text-davinci-003 model. I know openAI had an outage earlier this week. 

How can I reproduce the issue?

Does this happen on any repo? Any commits? With the same API key?

**Comment by nengqi** [comment] 2023-02-07 14:52
<img width="488" alt="image" src="https://user-images.githubusercontent.com/32950454/217276309-9d360e56-c631-4486-8b21-f8472d2c8ed4.png">
It worked until Feb 5, and then suddenly failed.
And yes, it happens on any repo, any commits, and I regen a new OPENAI API-key, still doesn't work.
I don't know if it's related to Network Conditions or anything else, so I don't know how to reproduce it. Now I'm going to create a new OpenAI account and try again.

**Comment by zurawiki** [comment] 2023-02-07 15:19
I can't currently repro this issue, so I can't really help with the information I have. Can others on your team reproduce the issue?

**Comment by nengqi** [comment] 2023-02-07 15:27
I created a new account and tried with the new OpenAI API-key and succeeded. There seems to be something wrong with my original account😢. Thx anyway!

**Comment by zurawiki** [comment] 2023-02-07 16:49
Glad to hear it works.  If there are no other followers,  can you close this issue?

**Closed** 2023-02-07 16:50 UTC
Labels: needs repro
